[package]
name = "linkmap"
version = "0.1.1"
edition = "2021"
description = "ğŸ¦€ï¸Linkmap file parse library"
license = "MIT"
repository = "https://github.com/everettjf/linkmap-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
symbolic-common = "8.6.0"
symbolic-demangle = "8.6.0"
